export const COULD_NOT_PING_SERVER = 'COULD_NOT_PING_SERVER'
export const ENDPOINT_NOT_FOUND = 'ENDPOINT_NOT_FOUND'
export const DB_UNAVAILABLE = 'DB_UNAVAILABLE'

export const CODE_MAP = {
    404: ENDPOINT_NOT_FOUND,
    666: DB_UNAVAILABLE,
    'NETWORK_ERROR': COULD_NOT_PING_SERVER
}