export const ALREADY_INSTALLED = 'ALREADY_INSTALLED'
export const NOT_INSTALLED_YET = 'NOT_INSTALLED_YET'
export const INSTALLER_PING = 'INSTALLER_PING'

export const NO_CONNECTION = 'NO_CONNECTION'
export const CONNECTION_SUCCESS = 'CONNECTION_SUCCESS'
